[project]
name = "pywebview-testbench"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pywebview>=6.1",
]

[dependency-groups]
dev = [
    "nuitka>=2.8.9",
    "pyinstaller>=6.17.0",
]
